<?php

define('BOOTSTRAP_DROPDOWN_FIELD_DIR', basename(dirname(__FILE__)));
define('BOOTSTRAP_DROPDOWN_FIELD_JAVASCRIPT', BOOTSTRAP_DROPDOWN_FIELD_DIR.'/javascript/');
define('BOOTSTRAP_DROPDOWN_FIELD_THIRDPARTY', BOOTSTRAP_DROPDOWN_FIELD_JAVASCRIPT.'thirdparty/');